### ISSUE TITLE
Segfault on Morden

### ISSUE THREAD

**Issue by soc1c** [etclabscore/go-ethereum#22]
```
2019-08-05 18:16:54 Sync      #1667477 of  #4767802 9f5279e9    47/1195/36 blk/txs/mgas sec  7/25 peers
2019-08-05 18:17:54 Sync      #1672193 of  #4767802 793bd1fc    78/ 440/37 blk/txs/mgas sec  7/25 peers
2019-08-05 18:18:54 Sync      #1676326 of  #4767802 c1d1212b    68/ 841/34 blk/txs/mgas sec  7/25 peers
2019-08-05 18:19:54 Sync      #1678690 of  #4767802 a0b96264    39/1162/32 blk/txs/mgas sec  7/25 peers
2019-08-05 18:20:54 Sync      #1681442 of  #4767802 5dab4279    45/1169/38 blk/txs/mgas sec  7/25 peers
2019-08-05 18:21:54 Sync      #1683943 of  #4767802 d4239601    41/1062/31 blk/txs/mgas sec  7/25 peers
2019-08-05 18:22:54 Sync      #1686875 of  #4767802 a9378f81    48/1062/36 blk/txs/mgas sec  7/25 peers
2019-08-05 18:23:54 Sync      #1690059 of  #4767802 0ee6dfbe    53/1088/32 blk/txs/mgas sec  7/25 peers
2019-08-05 18:24:54 Sync      #1692316 of  #4767802 207c4f6d    37/1256/33 blk/txs/mgas sec  7/25 peers
2019-08-05 18:25:54 Sync      #1694624 of  #4767802 fb337b77    38/1129/31 blk/txs/mgas sec  7/25 peers
2019-08-05 18:26:54 Sync      #1697015 of  #4767802 3e5aa2d1    39/1091/31 blk/txs/mgas sec  7/25 peers
2019-08-05 18:27:54 Sync      #1699199 of  #4767802 af8d33a3    36/1123/42 blk/txs/mgas sec  7/25 peers
2019-08-05 18:28:54 Sync      #1700507 of  #4767802 3cbe06a3    21/ 558/40 blk/txs/mgas sec  7/25 peers
2019-08-05 18:29:54 Sync      #1704693 of  #4767802 24df2065    69/ 394/39 blk/txs/mgas sec  7/25 peers
2019-08-05 18:30:54 Sync      #1707271 of  #4767802 d839d57d    42/ 628/30 blk/txs/mgas sec  7/25 peers
2019-08-05 18:31:54 Sync      #1710007 of  #4767802 f4bbded6    45/ 924/29 blk/txs/mgas sec  7/25 peers
2019-08-05 18:32:54 Sync      #1712106 of  #4767802 1c78ea55    34/1155/36 blk/txs/mgas sec  7/25 peers
2019-08-05 18:33:54 Sync      #1715791 of  #4767802 b0837fad    61/ 586/41 blk/txs/mgas sec  7/25 peers
2019-08-05 18:34:54 Sync      #1718916 of  #4767802 db9acf7f    52/ 721/49 blk/txs/mgas sec  7/25 peers
2019-08-05 18:35:54 Sync      #1721732 of  #4767802 89acfd59    46/ 870/28 blk/txs/mgas sec  7/25 peers
2019-08-05 18:36:54 Sync      #1724359 of  #4767802 91cce349    43/ 792/25 blk/txs/mgas sec  7/25 peers
2019-08-05 18:37:54 Sync      #1726192 of  #4767802 40ae8d17    30/ 660/21 blk/txs/mgas sec  7/25 peers
2019-08-05 18:38:54 Sync      #1728623 of  #4767802 44e7e3e5    40/ 642/29 blk/txs/mgas sec  7/25 peers
2019-08-05 18:39:54 Sync      #1728980 of  #4767802 155fe5c0     5/ 108/10 blk/txs/mgas sec  7/25 peers
2019-08-05 18:40:54 Sync      #1732179 of  #4767802 b8b7acec    53/ 879/40 blk/txs/mgas sec  7/25 peers
2019-08-05 18:41:54 Sync      #1732687 of  #4767802 129ec5f4     8/  39/ 7 blk/txs/mgas sec  7/25 peers
2019-08-05 18:42:54 Sync      #1734730 of  #4767802 180e7f4c    34/ 456/41 blk/txs/mgas sec  7/25 peers
2019-08-05 18:43:54 Sync      #1736261 of  #4767802 c6803c3e    25/ 380/78 blk/txs/mgas sec  7/25 peers
2019-08-05 18:44:54 Sync      #1739016 of  #4767802 a71f437b    45/ 653/31 blk/txs/mgas sec  7/25 peers
2019-08-05 18:45:54 Sync      #1742406 of  #4767802 296d7f96    56/ 824/33 blk/txs/mgas sec  7/25 peers
2019-08-05 18:46:54 Sync      #1745354 of  #4767802 34dba4d3    49/ 738/32 blk/txs/mgas sec  7/25 peers
2019-08-05 18:47:55 Sync      #1749411 of  #4767802 1a4ca3bd    67/ 491/24 blk/txs/mgas sec  7/25 peers
2019-08-05 18:48:55 Sync      #1753448 of  #4767802 2a02a0f7    67/ 417/25 blk/txs/mgas sec  7/25 peers
2019-08-05 18:49:54 Sync      #1756151 of  #4767802 39a2a3d1    45/ 977/34 blk/txs/mgas sec  7/25 peers
2019-08-05 18:50:54 Sync      #1758460 of  #4767802 85b7b09b    38/ 631/35 blk/txs/mgas sec  7/25 peers
2019-08-05 18:51:54 Sync      #1761619 of  #4767802 549f8437    52/ 759/34 blk/txs/mgas sec  8/25 peers
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa888f6]

goroutine 1161 [running]:
github.com/eth-classic/go-ethereum/core/state.(*StateObject).Address(0x0, 0x0, 0x0, 0x0)
	/home/user/.opt/getc-core/core/state/state_object.go:323 +0x16
github.com/eth-classic/go-ethereum/core.create(0x1169d20, 0xc0859fb440, 0x7f290c35f440, 0x0, 0x9732abdd21ff43cf, 0x94e40aec95021266, 0x9d292f39f58f40ac, 0xabd5f42833d9a510, 0xc08d4d8880, 0xd23, ...)
	/home/user/.opt/getc-core/core/execution.go:251 +0xe2
github.com/eth-classic/go-ethereum/core.Create(0x1169d20, 0xc0859fb440, 0x7f290c35f440, 0x0, 0xc08d4d8880, 0xd23, 0xd23, 0xc0a33ce580, 0xc0a33ce5a0, 0xc0a33ce5e0, ...)
	/home/user/.opt/getc-core/core/execution.go:230 +0x16a
github.com/eth-classic/go-ethereum/core.(*VMEnv).Create(0xc0859fb440, 0x7f290c35f440, 0x0, 0xc08d4d8880, 0xd23, 0xd23, 0xc0a33ce580, 0xc0a33ce5a0, 0xc0a33ce5e0, 0x203011, ...)
	/home/user/.opt/getc-core/core/vm_env.go:123 +0xcb
github.com/eth-classic/go-ethereum/core.(*StateTransition).TransitionDb(0xc044e68540, 0xc0859fb440, 0x115d0c0, 0xc02d83fb80, 0xc08e084240, 0xc044e68540, 0xc0859fb440, 0xc00ec43ad0)
	/home/user/.opt/getc-core/core/state_transition.go:228 +0xa03
github.com/eth-classic/go-ethereum/core.ApplyMessage(0x1169d20, 0xc0859fb440, 0x115d0c0, 0xc02d83fb80, 0xc08e084240, 0xc05d974000, 0xc0859fb440, 0xc0447011f0, 0xc0001e1120, 0xc0027f6780, ...)
	/home/user/.opt/getc-core/core/state_transition.go:134 +0x65
github.com/eth-classic/go-ethereum/core.ApplyTransaction(0xc0003b5b00, 0xc0000cb8c0, 0xc08e084240, 0xc000469590, 0xc05d974000, 0xc02d83fb80, 0xc08e084180, 0x0, 0x0, 0x0, ...)
	/home/user/.opt/getc-core/core/state_processor.go:116 +0x107
github.com/eth-classic/go-ethereum/core.(*StateProcessor).Process(0xc00006c000, 0xc02bfbcc60, 0xc000469590, 0x3a3a7ce954a7703b, 0x5e58c700a170a7a9, 0x0, 0x0, 0x0, 0x1, 0x0, ...)
	/home/user/.opt/getc-core/core/state_processor.go:88 +0x3e5
github.com/eth-classic/go-ethereum/core.(*BlockChain).InsertChain(0xc0000cb8c0, 0xc02b506000, 0x800, 0x800, 0xc02bb7db00)
	/home/user/.opt/getc-core/core/blockchain.go:1646 +0x1ea7
github.com/eth-classic/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc0001e49c0, 0xc02696a000, 0x800, 0x800, 0x800, 0x0)
	/home/user/.opt/getc-core/eth/downloader/downloader.go:1449 +0x5c9
github.com/eth-classic/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc0001e49c0, 0x55b54fa7c561709a, 0xc002250798)
	/home/user/.opt/getc-core/eth/downloader/downloader.go:1422 +0x79
github.com/eth-classic/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc0001e49c0, 0xc003099f20, 0xc0031aacb0)
	/home/user/.opt/getc-core/eth/downloader/downloader.go:583 +0x59
created by github.com/eth-classic/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/home/user/.opt/getc-core/eth/downloader/downloader.go:583 +0xaf

~/.opt/getc-core austin/executionrefactor 3h 16m 34s
❯ bin/geth --testnet --rpc
2019-08-05 22:20:40 Geth Classic version: v6.0.6-24-g6cc8fde
2019-08-05 22:20:40 Blockchain: Morden Testnet
2019-08-05 22:20:40 Chain database: /home/user/.ethereum-classic/morden/chaindata
2019-08-05 22:20:40 Blockchain upgrades configured: 7
2019-08-05 22:20:40   494000 Homestead
2019-08-05 22:20:40  1783000 GasReprice
2019-08-05 22:20:40  1885000 The DAO Hard Fork
2019-08-05 22:20:40  1915000 Diehard
2019-08-05 22:20:40  2000000 Gotham
2019-08-05 22:20:40  2300000 Defuse Difficulty Bomb
2019-08-05 22:20:40  4729274 Atlantis
2019-08-05 22:20:40 Using 21 configured bootnodes
2019-08-05 22:20:40 Use Sputnik EVM: false
2019-08-05 22:20:40 No etherbase set and no accounts found as default
2019-08-05 22:20:40 Allotted 1024MB cache and 1024 file handles to /home/user/.ethereum-classic/morden/chaindata
2019-08-05 22:20:42 Allotted 16MB cache and 16 file handles to /home/user/.ethereum-classic/morden/dapp
2019-08-05 22:20:42 Protocol Versions: [63 62], Network Id: 2, Chain Id: 62
2019-08-05 22:20:42 Genesis block: 0x0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303 (morden testnet)
2019-08-05 22:20:42 Local head header:     #1763244 [0x8e2be2…] TD=392735219237414
2019-08-05 22:20:42 Local head full block: #1763244 [0x8e2be2…] TD=392735219237414
2019-08-05 22:20:42 Local head fast block: #1763244 [0x8e2be2…] TD=392735219237414
2019-08-05 22:20:42 Starting server...
2019-08-05 22:20:42 Mapping network port udp:30303 -> 30303 (ethereum discovery) using NAT-PMP(192.168.0.1)
2019-08-05 22:20:42 UDP listening. Client enode: enode://d529883f7d66a96a98e0dab15371d8b58d84d81796c7ae28333faf49635e24348e2aecc26c33cb8dcd390129bf1a2af46e81e0eabd09d691b302df08429078b6@192.168.1.100:30303
2019-08-05 22:20:42 IPC endpoint opened: /home/user/.ethereum-classic/morden/geth.ipc
2019-08-05 22:20:42 HTTP endpoint: http://localhost:8545
2019-08-05 22:20:42 Debug log config: verbosity=5 log-dir=/home/user/.ethereum-classic/morden/log vmodule=*
2019-08-05 22:20:42 Display log config: display=3 status=sync=1m0s
2019-08-05 22:20:42 Machine log config: mlog=off
2019-08-05 22:20:42 Mapping network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(192.168.0.1)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa888f6]

goroutine 2364 [running]:
github.com/eth-classic/go-ethereum/core/state.(*StateObject).Address(0x0, 0x0, 0x0, 0x0)
	/home/user/.opt/getc-core/core/state/state_object.go:323 +0x16
github.com/eth-classic/go-ethereum/core.create(0x1169d20, 0xc002a6d860, 0x7ff08840f980, 0x0, 0x9732abdd21ff43cf, 0x94e40aec95021266, 0x9d292f39f58f40ac, 0xabd5f42833d9a510, 0xc00a1f4d80, 0xd23, ...)
	/home/user/.opt/getc-core/core/execution.go:251 +0xe2
github.com/eth-classic/go-ethereum/core.Create(0x1169d20, 0xc002a6d860, 0x7ff08840f980, 0x0, 0xc00a1f4d80, 0xd23, 0xd23, 0xc0045ce5a0, 0xc0045ce5c0, 0xc0045ce600, ...)
	/home/user/.opt/getc-core/core/execution.go:230 +0x16a
github.com/eth-classic/go-ethereum/core.(*VMEnv).Create(0xc002a6d860, 0x7ff08840f980, 0x0, 0xc00a1f4d80, 0xd23, 0xd23, 0xc0045ce5a0, 0xc0045ce5c0, 0xc0045ce600, 0x203000, ...)
	/home/user/.opt/getc-core/core/vm_env.go:123 +0xcb
github.com/eth-classic/go-ethereum/core.(*StateTransition).TransitionDb(0xc001d97c00, 0xc002a6d860, 0x115d0c0, 0xc019d42820, 0xc00972ccc0, 0xc001d97c00, 0xc002a6d860, 0xc01797d2c0)
	/home/user/.opt/getc-core/core/state_transition.go:228 +0xa03
github.com/eth-classic/go-ethereum/core.ApplyMessage(0x1169d20, 0xc002a6d860, 0x115d0c0, 0xc019d42820, 0xc00972ccc0, 0xc0141ca000, 0xc002a6d860, 0xc001d99110, 0xc0000ff120, 0xc00025ca80, ...)
	/home/user/.opt/getc-core/core/state_transition.go:134 +0x65
github.com/eth-classic/go-ethereum/core.ApplyTransaction(0xc00017db30, 0xc0002447e0, 0xc00972ccc0, 0xc017a402d0, 0xc0141ca000, 0xc019d42820, 0xc00972cc00, 0x0, 0x0, 0x0, ...)
	/home/user/.opt/getc-core/core/state_processor.go:116 +0x107
github.com/eth-classic/go-ethereum/core.(*StateProcessor).Process(0xc000f08e30, 0xc015abafc0, 0xc017a402d0, 0x3a3a7ce954a7703b, 0x5e58c700a170a7a9, 0x0, 0x0, 0xc0179a7f40, 0xc000bfd400, 0x50, ...)
	/home/user/.opt/getc-core/core/state_processor.go:88 +0x3e5
github.com/eth-classic/go-ethereum/core.(*BlockChain).InsertChain(0xc0002447e0, 0xc01b3396d0, 0x2, 0x2, 0xc005c10a00)
	/home/user/.opt/getc-core/core/blockchain.go:1646 +0x1ea7
github.com/eth-classic/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc0001d4ea0, 0xc01b3395f0, 0x2, 0x2, 0x2, 0xfa258e96f7d1b956)
	/home/user/.opt/getc-core/eth/downloader/downloader.go:1449 +0x5c9
github.com/eth-classic/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc0001d4ea0, 0x4830fe349d80fa12, 0xc019dc5f98)
	/home/user/.opt/getc-core/eth/downloader/downloader.go:1422 +0x79
github.com/eth-classic/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc0001d4ea0, 0xc019d253e0, 0xc0175cf750)
	/home/user/.opt/getc-core/eth/downloader/downloader.go:583 +0x59
created by github.com/eth-classic/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/home/user/.opt/getc-core/eth/downloader/downloader.go:583 +0xaf

~/.opt/getc-core austin/executionrefactor 36s
❯ 
```

**Comment by austinabell** [comment]
why open this issue here? This is just relating to the in progress PR, does not happen before the changes.

**Comment by soc1c** [comment]
Sorry, just wanted to post it somewhere
